[tasks.dev]
description = "Start live server"
run = "live-server --port=8080 --open=/"

[tasks.index]
description = "Regenerate root index.html"
run = "./scripts/generate-index.sh"

[tasks.new]
description = "Create new artifact with auto-incremented number"
run = """./scripts/create-artifact.sh"""
